version: 0.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    steps:
      - clone

      - run: wodby ci init $WODBY_BUILD_ID
      - run: wodby ci run -s node -- npm ci
      - run: wodby ci run -s node -- npm run check

      - run: wodby ci build node -f Dockerfile
      - run: wodby ci release
      - run: wodby ci deploy
